language: cpp
compiler: 
    - gcc
notifications:
    email: false
before_install:
    - sudo add-apt-repository ppa:staticfloat/julia-deps -y
    - sudo add-apt-repository ppa:staticfloat/julianightlies -y
    - sudo apt-get update -qq -y
    - sudo apt-get install libpcre3-dev julia -y
    - git config --global user.name "Travis User"
    - git config --global user.email "travis@example.net"
script:
    - julia -e 'versioninfo(); Pkg.init();'
    # uncomment when rened PR merged, and remove the next line that calls the forked repo
    - julia -e 'Pkg.add("Datetime"); Pkg.add("FactCheck"); Pkg.clone("git://github.com/milktrader/Series.jl.git"); Pkg.clone("git://github.com/JuliaQuant/MarketData.jl.git");'
#    - julia -e 'Pkg.add("Datetime"); Pkg.clone("git://github.com/rened/FactCheck.jl"); Pkg.clone("git://github.com/milktrader/Series.jl.git"); Pkg.clone("git://github.com/JuliaQuant/MarketData.jl.git");'
    - mkdir -p ~/.julia/Series
    - cp -R ./* ~/.julia/Series/
    - julia ./test/travis.jl
